apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: MTIz  # Base64 encoded password: echo -n '123' | base64
  mysql-database: bXlkYg==  # Base64 encoded database name: echo -n 'mydb' | base64
